Jumpscale/portal9

install.sh

-
-
**Version**: 
**Fixes**: #

install portal

---

JumpScale9Portal/data/models/Models.py
JumpScale9Portal/portal/PortalRest.py
JumpScale9Portal/portal/auth.py
JumpScale9Portal/portal/docgenerator/popup.py
JumpScale9Portal/portal/events.py
apps/portalbase/macros/page/audits/5_audits.py
apps/portalbase/wiki/System/.space/nav.wiki
apps/portalbase/wiki/System/Audits/Audit.wiki
apps/portalbase/wiki/System/Audits/Audits.wiki

Add support for tags in audits

Port audits macros

---

apps/portalbase/AYS/Details/Service.wiki

Fixes https://github.com/Jumpscale/jscockpit/issues/349

Missingrole

---

run_tests.sh
test.sh

-
-
**Version**: 
**Fixes**: #

stop using container name

---

run_tests.sh

-
-
**Version**: 
**Fixes**: #

No container name

---

JumpScale9Portal/data/models/Models.py
JumpScale9Portal/portal/ErrorHandler.py
JumpScale9Portal/portal/PortalServer.py
apps/portalbase/macros/page/ecos/1_ecos.py
apps/portalbase/macros/wiki/eco/1_eco.py
apps/portalbase/wiki/System/Error Conditions/Error Condition.wiki
apps/portalbase/wiki/System/Error Conditions/Error Conditions.wiki

Add ecos to js9portal

---

JumpScale9Portal/portal/datatables/PortalDataTables.py

Fix pagination in datatables

---

apps/portalbase/AYS/Details/Service.wiki

Resolves #28
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
-
-
**Version**: 
**Fixes**: #

Fixes bad indentation issue

---

install.sh
setup.py

-
-
**Version**: 
**Fixes**: #

903 master backport

---

JumpScale9Portal/portal/docgenerator/form.py

fix form.py error response

---

apps/portalbase/wiki/System/.space/nav.wiki

Add ecos in navmenu

---

apps/portalbase/system/system__docgenerator/methodclass/system_docgenerator.py

Obbey the group filter passed to the actor

---

JumpScale9Portal/data/models/Models.py

Make sure users by default get created in active mode

---

apps/portalbase/system/system__errorconditionhandler/methodclass/system_errorconditionhandler.py
apps/portalbase/system/system__errorconditionhandler/specs/actor.spec

Port actor to purge ecos

---

JumpScale9Portal/portal/docgenerator/PageHTML.py
apps/portalbase/macros/page/accordion/3_accordion.py
apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py
apps/portalbase/system/system__atyourservice/specs/actor.spec

https://github.com/Jumpscale/portal9/issues/5
-
-
**Version**: 
**Fixes**: #

fixes for updateBlueprints and the blueprints Editor

---

JumpScale9Portal/portal/html/GridDataTables.py

Caused datatable to fail in initialization.

Remove bootstrap pagination

---

JumpScale9Portal/portal/PageProcessor.py

https://github.com/Jumpscale/portal9/issues/43
-
-
**Version**: 
**Fixes**: #

fix multiple headers in proxy

---

JumpScale9Portal/portal/PortalServer.py

Fix loading params when doing a post with empty data

---

JumpScale9Portal/portal/PageProcessor.py
JumpScale9Portal/portal/PortalServer.py

-
-
**Version**: 
**Fixes**: #

apply proxy fixes from portal7

---

JumpScale9Portal/data/models/Models.py
JumpScale9Portal/portal/ErrorHandler.py
JumpScale9Portal/portal/events.py
apps/portalbase/macros/wiki/eco/1_eco.py
apps/portalbase/wiki/System/Error Conditions/Error Condition.wiki

When events fail send a link to eco object with the uniquekey
Store uniquekeys in the eco object.

Update handling of ecos

---

apps/portalbase/system/system__usermanager/methodclass/system_usermanager.py

https://docs.greenitglobe.com/openvcloud/openvcloud/issues/22
-
-
**Version**: 
**Fixes**: #

fix delete user

---

apps/portalbase/macros/page/create_space/1_create_space.py

Fixes #37  (wrong loaderfactory)

fix create_space macro use to correct loaderfactory

---

JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py

Prevent creation of duplicate users

---

JumpScale9Portal/data/models/Models.py
JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py
README.md
apps/portalbase/macros/page/group_edit/5_groupedit.py
apps/portalbase/macros/page/user_create/5_usercreate.py
apps/portalbase/macros/page/user_edit/5_useredit.py
apps/portalbase/macros/wiki/groups/1_groups.py
apps/portalbase/system/system__usermanager/methodclass/system_usermanager.py
apps/portalbase/system/system__usermanager/specs/actors.spec
apps/portalbase/wiki/System/Groups/Group/Group.wiki
apps/portalbase/wiki/System/Groups/Groups.wiki
apps/portalbase/wiki/System/Userlist/User/User.wiki
migration-script.py

- fixes for user API
- removing unnecessary data from user and group model
- Script for updating the database models
**Version**: 9.1.1
**Fixes**: #https://github.com/Jumpscale/portal9/issues/39

cleaning up user and group model

---

JumpScale9Portal/portal/docgenerator/PageHTML.py
apps/portalbase/system/system__usermanager/methodclass/system_usermanager.py
apps/portalbase/system/system__usermanager/specs/actors.spec
apps/portalbase/wiki/System/Groups/Group/Group.wiki

Fixes for editing group and specifying the groups during user creation
**Version**: 9.1.1
**Fixes**: #https://github.com/Jumpscale/portal9/issues/66

fix for updating group and creating users

---

JumpScale9Portal/portal/MacroExecutor.py

https://github.com/Jumpscale/portal9/issues/56

fix macro candidates needed for ovc

---

.travis.yml
.travis_ci/prepare.sh
install.sh
run_tests.sh
setup.py
test.sh
upload_image.sh

-
-
**Version**: 
**Fixes**: #

9.1.1 remove gigdir

---

install.sh
test.sh

https://github.com/Jumpscale/portal9/issues/65
-
-
**Version**: 
**Fixes**: #

fix portal install

---

.travis_ci/prepare.sh
run_tests.sh
upload_image.sh

**Fixes**: https://github.com/Jumpscale/ays9/issues/225

update test/build configs

---

JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py

-
-
**Version**: 
**Fixes**: openvcloud/openvcloud#10

Prevent duplicate user creation with the same email

---

docs/Howto/How-to-use-portal-client.md

**Fixes**: #https://github.com/Jumpscale/lib9/issues/28

docs for portal client

---

docs/GettingStarted/Installation.md
install.sh
test.sh

Updating to correct prefab portal module in the installation.

updating prefab installation

---

apps/portalbase/system/system__usermanager/methodclass/system_usermanager.py

issue #79 
- handled non-existing user error 
-
**Version**: 
**Fixes**: #

added error handling for the non-existing user

---

JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py
JumpScale9Portal/portal/PortalServer.py
JumpScale9Portal/portal/exceptions.py
docs/Configuration/Configuration.md
docs/Configuration/JWT-Support.md

Make it possible to pass JWT in authentication header
Make it possible to pass authkey via header

Add support for JWT during authentication

---

JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py

Allow setting the authkey while creating the user.
-
-
**Version**: 
**Fixes**: #

extend user create to allow setting the authkey.

---

JumpScale9Portal/portal/PortalServer.py
apps/portalbase/macros/page/explorer/1_main.py

Related to https://github.com/Jumpscale/core9/pull/94
**Version**: 9.3.0

install tools fs cleanup

---

JumpScale9Portal/portal/PortalServer.py
apps/portalbase/config.toml
apps/portalbase/portal_start.py

installing more than one portal through prefab
**Version**: 
9.3.0

add support for installing more than one portal

---

JumpScale9Portal/portal/docpreprocessor/DocPreprocessor.py
JumpScale9Portal/portal/portalloaders/ActorsLoader.py
JumpScale9Portal/portal/portalloaders/LoaderBase.py
JumpScale9Portal/portal/portalloaders/SpacesLoader.py

-
-
**Version**: 
**Fixes**: #94

Replace getDirName with getBaseName after stripping trailing slash

---

JumpScale9Portal/PortalFactory.py
JumpScale9Portal/tools/usermanager/UserManager.py

**Version**:  9.3.0
**Fixes**: #110

moving database handling to portal

---

JumpScale9Portal/portal/ErrorHandler.py

-
-
**Version**: 
**Fixes**: #

Fix redis bug
